In [53]:
import numpy as np

In [54]:
# Criar lista em Python

minhaLista = list(range(10))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
# Converter lista Python para array NumPy
 
arr = np.array(minhaLista)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# Criar arrays com NumPy

"""A função arange funciona da mesma forma que a função range do Python"""

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Criar array preenchido com 0

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [58]:
# Criar array preenchido com 1

arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [59]:
# Números aleatórios inteiros em NumPy

"""
    Parâmetros:
    1: Início do intervalo
    2: Fim do intervalo
    3: Quantidade de elementos

"""

arr = np.random.randint(0, 100, 10)
arr

array([63, 15, 57, 35, 39, 18, 66, 86, 83, 24])

In [60]:
# Arredondamento

"""
    Parâmetros:
    1: Número a ser arredondado
    2: Quantidade de casa decimais
"""

num = np.round(6.54745, 2)
num

6.55

In [61]:
# Consultando e definindo estruturas dos arrays

arr = np.random.randint(0, 10, 6)
                        
# Consulta:                         
print(arr.shape)

# Definição de matriz com duas linhas e três colunas
arr.shape = (2,3)
print(arr)
print(arr.shape)


(6,)
[[2 0 0]
 [7 6 4]]
(2, 3)


In [62]:
# Máximos e mínimos

arr = np.random.randint(0, 10, 6)

print(arr)
print(arr.max())
print(arr.min())

# Indíces onde se encontram o maior e menor elemento respectivamente
print(arr.argmax())
print(arr.argmin())

[3 9 0 4 7 3]
9
0
1
2


In [63]:
# Copiando arrays

arr1 = np.random.randint(0, 10, 6)
arr2 = arr1.copy()

print(arr1)
print(arr2)

[5 0 2 5 7 9]
[5 0 2 5 7 9]


In [64]:
# Slices em arrays

print("Array original")
arr = np.arange(36)
print(arr)

print("\nMatriz 6x6")
arr.shape = 6, 6
print(arr)

print("\nExibindo o primeiro elemento (primeira linha)")
print(arr[0])

print("\nBuscando entre linhas e colunas (todos os primeiros elementos de todas as linhas)")
print(arr[:, 0])

Array original
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]

Matriz 6x6
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Exibindo o primeiro elemento (primeira linha)
[0 1 2 3 4 5]

Buscando entre linhas e colunas (todos os primeiros elementos de todas as linhas)
[ 0  6 12 18 24 30]


In [65]:
# Filtrar valores

arr = np.arange(36)
arr.shape = 6, 6
print(arr)

"""
    Criando outra matriz contendo apenas boleanos para determinada condição. 
    Nesse caso, retornará True apenas os elementos pares
"""

arr2 = arr % 2 == 0
print(arr2)

# Filtrando os valores

print(arr[arr2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


In [66]:
# Soma de arrays

arr = np.arange(36)
print(np.sum(arr))

630


In [67]:
# Desvio padrão de arrays

arr = np.arange(36)
print(np.std(arr))

10.388294694831615


In [68]:
# Soma de linhas e colunas

arr = np.arange(36)
arr.shape = (6, 6)
print(arr)

# Soma de colunas

print(arr.sum(axis=0))

# Soma de linhas

print(arr.sum(axis=1))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[ 90  96 102 108 114 120]
[ 15  51  87 123 159 195]
